# CS 115 - Introduction to Programming in Python
## Lab 06

### Lab Objectives:  Two-D Lists, numpy arrays

**Instructions:** In this lab, you will use Jupyter Notebook. Write your solutions in this notebook, rename it as SS_Lab06_Surname_FirstName.ipynb where SS is the section number 01, 02, 03, etc. and upload it to the Lab06 assignment on Moodle before the end of your lab session. 

## <font color=red>** Question 1**</font> 
### You will write code to store and manipulate two dimensional lists of data. Complete the steps below.

Write a function, ***valuesBefore()*** that takes a two-dimensional list of integers and an integer search value as parameters.  The function should search each column in the two-dimensional list, and count the number of values that come before the first occurrence of the search value in each column.  If the search value is not found in a column, the count should be -1. Store the counts in a one-dimensional list.  The function should return the list which stores the counts.

In [29]:
def valuesBefore(myList, search):
    countList = [-1] * (len(myList))
    print(myList[4][3])
    for vertical in range(len(myList)):
        for horizontal in range(len(myList[vertical]) ):
            if (myList[vertical][horizontal] == search):
                countList[vertical] = horizontal
                break
    return countList

Using the function above, write code that initializes a two dimensional list of integer values.  Input a value from the user and display the counts of the values before, using the function defined above. See sample output below:

Sample Run:
Two D List of Values:

[3, 4, 8, 6]

[6, 2, 2, 5]

[8, 7, 7, 9]

[4, 6, 2, 3]

[8, 9, 3, 8]

Enter search value: 8

Values before search value in each column:  [2, -1, 0, 4]


In [91]:
myList = [[3,4,8,6], [6,2,2,5], [8,7,7,9], [4,6,2,3], [8,9,3,8]]
print("Two D List of Values: ")
for n in myList:
    print (n)

search = int(input("Enter search value: "))
print("Values before search value in each column:  ", valuesBefore(myList, search))

Two D List of Values: 
[3, 4, 8, 6]
[6, 2, 2, 5]
[8, 7, 7, 9]
[4, 6, 2, 3]
[8, 9, 3, 8]
Enter search value: 2
8
Values before search value in each column:   [-1, 1, -1, 2, -1]


# ### You will use numpy arrays to store and manipulate data from files.  Complete the steps listed below:

import numpy for use in your code

In [48]:
import numpy as np

Read data from the files product.txt, which contains the prices of a number of products and quantity.txt, which stores their quantities, into two numpy arrays.

In [68]:
product = np.loadtxt("product.txt", skiprows=1)
quantity = np.loadtxt("quantity.txt", dtype='int')

Display the prices and quantities.

In [69]:
print("Products: \n", product)
print("Quantity: \n", quantity)

Products: 
 [[ 87.   66.   22.5  90.  105. ]
 [100.   10.   22.   87.   45. ]]
Quantity: 
 [[100  57  22  96 115]
 [ 46 115  54  20  70]]


Increase the price of each product by 15% and display the updated prices.

In [77]:
product= np.multiply(product, 1.15)
print("Products: \n", product)
print("Quantity: \n", quantity)

Products: 
 [[100.05   75.9    25.875 103.5   120.75 ]
 [115.     11.5    25.3   100.05   51.75 ]]
Quantity: 
 [[100  57  22  96 115]
 [ 46 115  54  20  70]]


Find and store the totals in a new array by multiplying the prices by the quantities and display the totals.

In [80]:
totals = np.multiply(product, quantity)
print("Totals: \n", totals)

Totals: 
 [[10005.    4326.3    569.25  9936.   13886.25]
 [ 5290.    1322.5   1366.2   2001.    3622.5 ]]


Save the totals to a file, totals.txt

In [81]:
np.savetxt("totals.txt", totals)

Decrease each quantity in the array by 10 and save to a file, updated_quantity.txt

In [82]:
updatedQuantity = numpy.subtract(quantity, 10)
np.savetxt("updated_quantity.txt", updatedQuantity)

Calculate the percent change of each quantity and store in a new array. For each quantity display the percent change.

In [87]:
difference = numpy.subtract(quantity, updatedQuantity)
pChange = numpy.divide(difference, quantity)
pchange = numpy.divide(pChange, 100)
print("%change in them")
print(pChange.reshape((10,1)))

%change in them
[[0.1       ]
 [0.1754386 ]
 [0.45454545]
 [0.10416667]
 [0.08695652]
 [0.2173913 ]
 [0.08695652]
 [0.18518519]
 [0.5       ]
 [0.14285714]]


Calculate and display the total quantities for each row.

In [88]:
print(np.sum(quantity, axis=0))

[146 172  76 116 185]


Calculate and display the total quantities for each column.

In [90]:
print((np.sum(quantity, axis=1)).reshape((2,1)))

[[390]
 [305]]
